frontend:
  build: ./frontend
  command: nginx -g "pid /tmp/nginx.pid; daemon off;"
  volumes:
    - ./frontend/dist:/srv/rc/app
  ports:
    - "1337"
  environment:
    VIRTUAL_HOST: raidcomp.xmyno.me
    VIRTUAL_PORT: 80

backend:
  build: ./backend
  command: node --harmony /srv/raidcomp/app.js
  links:
    - mongo
  volumes:
    - ./backend/app:/srv/raidcomp/app
    - ./backend/app.js:/srv/raidcomp/app.js
  ports:
    - "5000"
  environment:
    VIRTUAL_HOST: api.raidcomp.xmyno.me
    VIRTUAL_PORT: 80

mongo:
  image: mongo
