proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock

frontend:
  build: ./frontend
  command: nginx -g "pid /tmp/nginx.pid; daemon off;"
  volumes:
    - ./frontend/dist:/srv/rc/app
    #- ./log/frontend:/var/log
  ports:
    - "1337:1337"
  environment:
    VIRTUAL_HOST: raidcomp.dev

backend:
  build: ./backend
  command: node --harmony /srv/raidcomp/app.js
  links:
    - mongo
  volumes:
    - ./backend/app:/srv/raidcomp/app
    - ./backend/app.js:/srv/raidcomp/app.js
  ports:
    - "5000:5000"
  environment:
    VIRTUAL_HOST: api.raidcomp.dev

mongo:
  image: mongo
