# proxy:
#     image: jwilder/nginx-proxy
#     ports:
#         - "80:80"
#     volumes:
#         - /var/run/docker.sock:/tmp/docker.sock

frontend:
    build: ./frontend
    ports:
        - "80:80"
    # environment:
    #     VIRTUAL_HOST:

backend:
    build: ./backend
    command: node --harmony /srv/rc/app.js
    links:
        - mongo
    volumes:
        - ./backend:/srv/rc
    ports:
        - "5000:5000"
    # environment:
    #     VIRTUAL_HOST:

mongo:
    image: mongo
